version: 2.1

parameters:
  run_build:  # Boolean parameter to control running the build job
    type: boolean
    default: false
  run_test:   # Boolean parameter to control running the test job
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
    when: << pipeline.parameters.run_build >>

  test:  # New job definition indented further
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
      when: << pipeline.parameters.run_test >>

workflows:
  build_and_test_deploy:  # We can keep the workflow name for future use
    jobs:
      - build
      - test:
          requires:
            - build
          # Removed the deploy job section