version: 2.1

parameters:
  run_build:
    type: boolean
    default: false
  run_test:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - when:
          condition: << pipeline.parameters.run_build >>
          steps:
            - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - when:
          condition: << pipeline.parameters.run_test >>
          steps:
            - run: python tests.py

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
