version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold_approval:
          type: approval # Approval step to manually trigger next actions (if any)
          requires:
            - test
